export const allSkills = [
  { label: "JavaScript" },
  { label: "React.js" },
  { label: "Next.js" },
  { label: "Node.js" },
  { label: "Express.js" },
  { label: "TypeScript" },
  { label: "HTML" },
  { label: "CSS" },
  { label: "Tailwind CSS" },
  { label: "Redux" },
  { label: "Firebase" },
  { label: "MongoDB" },
  { label: "MySQL" },
  { label: "PostgreSQL" },
  { label: "Git" },
  { label: "GitHub" },
  { label: "REST API" },
  { label: "GraphQL" },
  { label: "Figma" },
  { label: "UI/UX Design" },
  { label: "Adobe Photoshop" },
  { label: "Canva" },
  { label: "SEO" },
  { label: "Digital Marketing" },
  { label: "Content Writing" },
  { label: "Copywriting" },
  { label: "Communication" },
  { label: "Teamwork" },
  { label: "Problem Solving" },
  { label: "Time Management" },
  { label: "Leadership" },
  { label: "Critical Thinking" },
  { label: "Creativity" },
  { label: "Adaptability" },
  { label: "Python" },
  { label: "Java" },
  { label: "C++" },
  { label: "C#" },
  { label: "PHP" },
  { label: "SQL" },
  { label: "AWS" },
  { label: "Docker" },
  { label: "Kubernetes" },
  { label: "Linux" },
  { label: "Machine Learning" },
  { label: "Data Analysis" },
  { label: "Excel" },
  { label: "Project Management" },
  { label: "Agile" },
  { label: "Scrum" },
  { label: "JIRA" },
  { label: "Customer Service" },
  { label: "Sales" },
  { label: "Negotiation" },
  { label: "Networking" },
  { label: "Public Speaking" },
  { label: "Social Media Management" },
  { label: "Video Editing" },
  { label: "Photography" },
  { label: "Illustrator" },
  { label: "After Effects" },
  { label: "Microsoft Office" },
  { label: "WordPress" },
  { label: "Flutter" },
  { label: "React Native" },
  { label: "Kotlin" },
  { label: "Swift" },
  { label: "Testing" },
  { label: "Jest" },
  { label: "Cypress" },
  { label: "Postman" },
  { label: "APIs" },
  { label: "Problem Solving" },
  { label: "Collaboration" },
  { label: "Attention to Detail" },
  { label: "Decision Making" },
  { label: "Analytical Thinking" },
  { label: "Research" },
  { label: "Business Strategy" },
  { label: "Finance" },
  { label: "Accounting" },
  { label: "Marketing" },
  { label: "Customer Relations" },
  { label: "Operations Management" },
  { label: "HR Management" },
  { label: "Data Visualization" },
  { label: "Power BI" },
  { label: "Tableau" },
  { label: "Cloud Computing" },
  { label: "Cybersecurity" },
  { label: "Ethical Hacking" },
  { label: "Network Security" },
  { label: "Data Entry" },
  { label: "Documentation" },
  { label: "Problem Diagnosis" },
  { label: "Fast Learner" },
  { label: "Adaptability" },
  { label: "Empathy" },
  { label: "Organization" },
  { label: "Presentation Skills" },
  { label: "Leadership" },
  { label: "Patient Care" },
  { label: "Medical Terminology" },
  { label: "Clinical Research" },
  { label: "Phlebotomy" },
  { label: "CPR" },
  { label: "First Aid" },
  { label: "Anatomy" },
  { label: "Physiology" },
  { label: "Pharmacology" },
  { label: "Medical Coding" },
  { label: "Electronic Health Records (EHR)" },
  { label: "Nursing" },
  { label: "Surgery Assistance" },
  { label: "Laboratory Testing" },
  { label: "Patient Counseling" },
  { label: "Health Education" },
  { label: "Public Health" },
  { label: "Nutrition" },
  { label: "Infection Control" },
  { label: "Emergency Care" },
];
