-- AlterTable
ALTER TABLE "Resume" ALTER COLUMN "professionalSummary" DROP NOT NULL,
ALTER COLUMN "skills" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "personalInfo" DROP NOT NULL,
ALTER COLUMN "workExperience" SET DEFAULT ARRAY[]::JSONB[],
ALTER COLUMN "education" SET DEFAULT ARRAY[]::JSONB[],
ALTER COLUMN "projects" SET DEFAULT ARRAY[]::JSONB[];
